services:
  pgvector:
    image: 'ankane/pgvector:latest'
    environment:
      - 'POSTGRES_DB=aidocs'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
