spring:
  application:
    name: aidocs
  datasource:
    url: jdbc:postgresql://localhost:5432/aidocs
    username: admin
    password: password
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
#  main:
#    banner-mode: off
#logging:
#  level:
#    root: off
